install.packages("GenABEL") 
install.packages("dNdScv") 
install.packages("sigfit") 
library(devtools); install_github("im3sanger/dndscv")
library(devtools); install_github("cran/GenABEL")
library(devtools); install_github("kgori/sigfit")
