library("dplyr")
library('rvest')
library("xml2")
library("httr")
url= "https://scholar.google.com/scholar?as_ylo=2019&q=rheumatoid+arthritis&hl=en&as_sdt=0,50"
resp <- httr::GET(url)
http_type(resp)
html<-read_html(resp)
xml_name(html)
line<-xml_text(html)
newline<-gsub("  ","\n",line)
write.table(newline,file="output.txt",sep="\t")
getwd()


library("scholar")
ids <- c("4tS95wQAAAAJ")
compare_scholar_careers(ids,career = TRUE)
get_citation_history(ids)
network<-get_coauthors(ids,n_coauthors = 6, n_deep = 2)
plot_coauthors(network, size_labels = 5)
get_complete_authors(id, pubid)
get_num_articles(ids)
get_num_distinct_journals(ids)
get_num_top_journals(ids)
get_oldest_article(ids)
get_profile(ids)
get_publications(ids, cstart = 0, pagesize = 100, flush = FALSE)
predict_h_index(ids)

